# Add our internal APT package repository to the sources
- name: add PGP signing key for the third-party repository providing Oracle's Java
  apt_key: keyserver=keyserver.ubuntu.com id=7B2C3B0889BF5709A105D03AC2518248EEA14886
- name: adding our private APT repository
  apt_repository: repo='ppa:webupd8team/java' state=present
- name: Accept Oracle License
  debconf: name={{ item }} question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
  with_items:
    - oracle-java6-installer
    - oracle-java7-installer
    - oracle-java8-installer
- name: Install Oracle's Java JRE
  apt: name=oracle-java8-installer state=present
