# Add our internal APT package repository to the sources
- name: add PGP signing key for the third-party repository providing Oracles Java
  apt_key: keyserver=keyserver.ubuntu.com id=EEA14886
  sudo: yes

- name: adding java ppa
  apt_repository: repo='ppa:webupd8team/java' state=present
  sudo: yes

- name: Accept Oracle License
  debconf: name={{ item }} question='shared/accepted-oracle-license-v1-1' value='true' vtype='select'
  with_items:
    - oracle-java6-installer
    - oracle-java7-installer
    - oracle-java8-installer
  sudo: yes

- name: Install Oracles Java JRE
  apt: name=oracle-java8-installer
       state=installed
  sudo: yes

