---
- hosts: kauai
  roles:
    - role: kerberos-keytabs
      tags: kerberos_keytabs
    - role: ad-credential-files
      tags: ad-credentials
  vars:
    - ad_username: lwinderling
  vars_prompt:
    - name: "ad_password"
      prompt: "Please, enter your AD password."
      private: yes
