- hosts: my-computers
  remote_user: lars
  sudo: no
  roles:
    - role: run-always
      tags: always
    - role: basics
      tags: basics
    - role: git-config
      tags: [git, git-config]
    - role: zsh
      tags: zsh
    - role: vim
      tags: vim
    - role: gui-basics
      tags: gui-basics
    - role: ssh-config
      tags: [ssh, ssh-config]
    - role: awesome
      tags: awesome
    - role: administration
      tags: administration
    - role: wine
      tags: wine
    - role: pyvenvs
      tags: pyvenvs
