- hosts: my-computers
  remote_user: lars
  sudo: yes
  vars:
    reinstall_awesome: no
    reinstall_heidi: no
    reinstall_vimrc: no
    home_dir: /home/lars
    awesome:
      config_dir: "{{ home_dir }}/.config/awesome"
      theme_dir: "{{ home_dir }}/.config/awesome/themes"
  roles:
    - role: run-before-installations
      sudo: no
      tags: always
    - role: extended-installations
      tags: installations
    - role: desktop-commons
      tags: desktop-commons
      remote_user: lars
    - role: gitconfig
      sudo: no
      tags: git
