- hosts: kauai

- include: awesome.yml
- include: base.yml
- include: git.yml
- include: lvm.yml # test that
- include: pyvenvs.yml
- include: shell.yml
- include: ssh-config.yml
- include: vim.yml
- include: wine.yml
- include: android.yml

  # FIXME
- hosts: kauai
  vars:
    binary: deb_list.skype.binary
    url: deb_list.skype.url
  roles:
    - download-and-install-deb

- hosts: kauai
  vars:
    binary: deb_list.spotify.binary
    url: deb_list.spotify.url
  roles:
    - download-and-install-deb
