- hosts: my-computers
  remote_user: lars
  vars:
    local_config_dir: "{{ home_dir }}/.config"
    awesome:
      terminal: xfce4-terminal
      theme: my-theme
      config_dir: "{{ home_dir }}/.config/awesome"
      theme_dir: "{{ home_dir }}/.config/awesome/themes"
      autostart:
        - prg: light-locker
        - prg: xfce4-power-manager
        - prg: nm-applet
      shortcuts:
        - cmd: xflock4
          mode: spawn
          modkey: yes
          extrakey: "Control"
          key: l
  roles:
    - role: run-before-installations
      tags: always
    - role: extended-installations
      tags: installations
      sudo: yes
    - role: desktop-commons
      tags: desktop-commons
      sudo: yes
    - role: gitconfig
      tags: git
    - role: zsh
      tags: zsh
    - role: vim
      tags: vim
    - role: gui-basics
      tags: gui-basics
    - role: ssh-config
      tags:
        - ssh
        - ssh-config
