awesome:
  terminal: xfce4-terminal
  theme: my-theme
  config_path: "{{ ansible_user_dir }}/.config/awesome"
  theme_dir: "{{ ansible_user_dir }}/.config/awesome/themes"
  autostart:
    - prg: light-locker
    - prg: xfce4-power-manager
    - prg: nm-applet
  shortcuts:
    - cmd: xflock4
      mode: spawn
      modkey: yes
      extrakey: "Control"
      key: l
  build_params:
    DCMAKE_PREFIX_PATH: /usr
    DSYSCONFDIR: /etc
  deps:
    - cmake
    - liblua5.1-dev
    - imagemagick
    - libxcb-randr0-dev
    - libxcb-xtest0-dev
    - libxcb-xinerama0-dev
    - libxcb-shape0-dev
    - libxcb-keysyms1-dev
    - libxcb-icccm4-dev
    - libx11-xcb-dev
    - lua-lgi-dev
    - libstartup-notification0-dev
    - libxdg-basedir-dev
    - libxcb-image0-dev
    - libxcb-util0-dev
    - libgdk-pixbuf2.0-dev
    - lua5.1
    - libxcb-cursor-dev
    - libcairo2-dev
    - libdbus-1-dev
