- name: check if awesome has been installed
  shell: |
    if [ {{ awesome_force_install }}]; then
      exit 1
    else
      type awesome >/dev/null 2>&1
      && awesome --version
      | grep -F "v{{ awesome.version }}"
      >/dev/null 2>&1
    fi
  changed_when: false
  ignore_errors: true
  register: awesome_installed

- include: build-deps.yml
  when: awesome_installed.rc > 0

- include: download.yml
  when: awesome_installed.rc > 0

- include: make.yml
  when: awesome_installed.rc > 0

- include: vicious.yml
  tags: configure-awesome
  when: awesome_installed.rc > 0
