wine:
  prefix_dir: /usr/local/wine
  lvm:
    vg: vgroot
    lv: lvwine
    size: 2G
  user: wine-user
  group: wine
  prefixes:
    - name: heidi
      download_url: "http://www.heidisql.com/installers/HeidiSQL_9.2.0.4947_Setup.exe"

