- name: install zsh from apt repository
  apt: name=zsh
       state=latest
  sudo: yes
  when: not all_cmds.results|has_cmd('zsh')

- name: install oh-my-zsh
  shell: wget https://raw.github.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O - | sh
  when: not all_cmds.results|has_cmd('ohmyzsh')

- name: set zsh as default shell
  user: user={{ ansible_user_id }}
        shell=/usr/bin/zsh
  sudo: yes

- name: create config dir for zsh
  file: path={{ zsh.config_path }}
        state=directory

- name: copy zsh files into place
  copy: src={{ item.src }}
        dest={{ item.dest }}
  with_items:
    - src: dot.zshrc
      dest: "{{ zsh.rc }}"
    - src: autocomplete
      dest: "{{ zsh.config_path }}"
    - src: fns
      dest: "{{ zsh.config_path }}"
