- name: check if program has been installed
  shell: type -p "{{ binary }}"
  changed_when: false
  ignore_errors: true
  register: proram_installed

- include: install.yml
  when: program_installed.rc > 0
