- name: check if program has been installed
  shell: type "{{ binary }}"
  changed_when: false
  ignore_errors: true
  register: program_installed

- include: install.yml
  when: program_installed.rc > 0
