---
- name: setup ~/bin
  file: path="{{ ansible_user_dir }}/bin"
        state=directory
        owner="{{ ansible_user_id }}"
        group="{{ ansible_user_id }}"

- name: Configure .gitconfig file
  template: src=dot.gitconfig.j2
            dest="{{ ansible_user_dir }}/.gitconfig"

- name: Copy further files into place
  copy: src=diffconflicts
        dest="{{ ansible_user_dir }}/bin/diffconflicts"
        mode=0755
