- name: create all additional user groups
  tags:
    - administration
  group: name={{ item.name }}
         state={{ item.state|default('present') }}
         system={{ item.system|default('no') }}
  with_items:
    administration.groups

- name: create all additional users accounts
  tags:
    - administration
  user: name={{ item.name }}
        group={{ item.group|default(omit) }}
        groups={{ item.groups|default(omit) }}
        state={{ item.state|default('present') }}
        append={{ item.append|default('yes') }}
        createhome={{ item.createhome|default(omit) }}
        move_home={{ item.move_home|default(omit) }}
        remove={{ item.remove|default('no') }}
        shell={{ item.shell|default(omit) }}
        system={{ item.system|default('no') }}
  with_items:
    administration.users
