---

- name: Configure .gitconfig file
  tags: gitconfig
  template: src=gitconfig.j2
            dest=~/.gitconfig

- name: Copy further files into place
  tags: gitconfig
  copy: src=diffconflicts
        dest=/usr/local/bin
        mode=0755
  sudo: yes
