- name: create vim-related folders
  file: path={{ item }}
        state=directory
  with_items:
    - "{{ vim.resources }}"
    - "{{ vim.ftplugin }}"
    - "{{ vim.syntax }}"

- name: create vim-related executables
  copy: src={{ item }}
        dest={{ vim.bin_path }}
        force=yes
  with_fileglob:
    bin/*

- name: copy custom .vim files
  copy: src="{{ item }}"
        dest="{{ vim.resources }}"
        force=yes
  with_fileglob:
    custom/*

- name: copy .vimrc
  tags: vimrc
  copy: src=dot.vimrc
        dest="{{ ansible_user_dir }}/.vimrc"

- name: template vim files
  template: src={{ item.src }}
            dest={{ item.dest }}
  with_items:
    - src: bundles.vim.j2
      dest: "{{ vim.resources }}/bundles.vim"
    - src: maps.vim.j2
      dest: "{{ vim.resources }}/maps.vim"
