- name: install vim-gtk from apt-repositories (-gtk for xterm-clipboard support)
  tags:
    - apt
  apt: name={{ item }}
       state=latest
  with_items:
    - vim-gtk

- name: install neobundle for vim
  shell: "curl https://raw.githubusercontent.com/Shougo/neobundle.vim/master/bin/install.sh | sh"
  args:
    creates: "{{ vim.bundles }}/neobundle.vim"

- name: create vim-related folders
  file: path={{ item }}
        state=directory
        mode=0775
  with_items:
    - "{{ vim.resources }}"
    - "{{ vim.ftplugin }}"
    - "{{ vim.syntax }}"

- name: copy vim-related files into place
  copy: src={{ item.src }}
        dest={{ item.dest }}
        force=yes
  with_items:
    - src: dot.vimrc
      dest: "{{ ansible_user_dir }}/.vimrc"
    - src: funcs.vim
      dest: "{{ vim.resources }}"

- name: copy ftplugin files into place
  copy: src={{ item }}
        dest={{ vim.ftplugin }}
  with_fileglob:
    ftplugin/*.vim

- name: install vimchat dependencies
  tags:
    - vimchat
  apt: name={{ item }}
       state=latest
       install_recommends=no
  with_items:
    - python-xmpp
    - python-notify
    - python-dns

- name: download silversearcher-ag source from github
  tags: ag
  git: repo={{ vim.ag.download_url }}
       dest=/tmp/silversearcher-ag
  when: reinstall_vim is defined or not all_cmds.results|has_cmd('ag')

- name: install silversearcher dependencies
  tags:
    - silversearcher
    - ag
  sudo: yes
  apt: name={{ item }}
       state=latest
  with_items:
    vim.ag.deps
  when: reinstall_vim is defined or not all_cmds.results|has_cmd('ag')

- name: install silversearcher-ag from source
  tags:
    - silversearcher
    - ag
  shell: ./build.sh && sudo make install
  args:
    chdir: /tmp/silversearcher-ag
  when: reinstall_vim is defined or not all_cmds.results|has_cmd('ag')

- name: create vim-related executables
  tags:
    - vim-bin
  copy: src={{ item }}
        dest={{ vim.bin_path }}
        mode=0775
        force=yes
  with_fileglob:
    bin/*
