- name: install vim-gtk from apt-repositories (-gtk for xterm-clipboard support)
  tags:
    - apt
  apt: name={{ item }}
       state=latest
  with_items:
    - vim-gtk

- name: install neobundle for vim
  shell: "curl https://raw.githubusercontent.com/Shougo/neobundle.vim/master/bin/install.sh | sh"
  args:
    creates: "{{ vim.bundles }}/neobundle.vim"

- name: create vim-related folders
  file: path={{ item }}
        state=directory
        mode=0775
  with_items:
    - "{{ vim.resources }}"
    - "{{ vim.ftplugin }}"
    - "{{ vim.syntax }}"

- name: template vim files
  template: src={{ item.src }}
            dest={{ item.dest }}
  with_items:
    - src: dot.vimrc.j2
      dest: "{{ ansible_user_dir }}/.vimrc"
    - src: maps.vim.j2
      dest: "{{ vim.resources }}/maps.vim"
    - src: funcs.vim.j2
      dest: "{{ vim.resources }}/funcs.vim"

- name: create dirs for assembling ftplugin files later on
  file: dest={{ vim.tmp_dir }}/{{ item|basename }}
        state=directory
        mode=0775
        owner={{ ansible_user_id }}
        group={{ ansible_user_id }}
  with_fileglob:
    ftplugin/*.vim

- name: copy ftplugin files into tmp dir
  copy: src={{ item }}
        dest={{ vim.tmp_dir }}/{{ item|basename }}/99_main.vim
  with_fileglob:
    ftplugin/*.vim

- name: template neobundle sources for ftplugins
  template: src=neobundle-source.vim.j2
            dest={{ vim.tmp_dir }}/{{ item|basename }}/10_neobundle-sources.vim
  with_fileglob:
    ftplugin/*.vim

- name: concat neobundle sources and ftplugin files
  assemble: src={{ vim.tmp_dir }}/{{ item|basename }}
            dest={{ vim.ftplugin }}/{{ item|basename }}
            remote_src=yes
            mode=0664
            owner={{ ansible_user_id }}
            group={{ ansible_user_id }}
  with_fileglob:
    ftplugin/*.vim
  notify:
    - remove ftplugin tmp dir

- name: install vimchat dependencies
  tags:
    - vimchat
  apt: name={{ item }}
       state=latest
       install_recommends=no
  with_items:
    - python-xmpp
    - python-notify
    - python-dns

- name: download silversearcher-ag source from github
  git: repo={{ vim.ag.download_url }}
       dest=/tmp/silversearcher-ag
  when: reinstall_vim is defined or not all_cmds.results|has_cmd('ag')

- name: install silversearcher dependencies
  tags:
    - silversearcher
    - ag
  sudo: yes
  apt: name={{ item }}
       state=latest
  with_items:
    vim.ag.deps
  when: reinstall_vim is defined or not all_cmds.results|has_cmd('ag')

- name: install silversearcher-ag from source
  tags:
    - silversearcher
    - ag
  shell: ./build.sh && sudo make install
  args:
    chdir: /tmp/silversearcher-ag
  when: reinstall_vim is defined or not all_cmds.results|has_cmd('ag')

- name: create vim-related executables
  tags:
    - vim-bin
  copy: src={{ item }}
        dest={{ vim.bin_path }}
        mode=0775
        force=yes
  with_fileglob:
    bin/*
