- name: install vimchat dependencies
  tags:
    - vimchat
  apt: name={{ item }}
       state=present
       install_recommends=no
  with_items:
    - python-xmpp
    - python-notify
    - python-dns
