---
- name: Set up logical volumes
  lvol:
    vg="{{item.vg|default(lvm_vars.vg)}}"
    lv="{{item.lv}}"
    size="{{item.size}}"
  when: lvm_vars.volumes is defined and
        (lvm_vars.vg is defined or lvm_vars.vgs is defined)
  with_items:
    "{{ lvm_vars.volumes }}"

- name: Format logical volumes
  filesystem:
    fstype="{{item.fstype|default('ext4')}}"
    dev="/dev/{{item.vg|default(lvm_vars.vg)}}/{{item.lv}}"
  with_items:
    "{{ lvm_vars.volumes }}"
