---
- name: Unmount logical volumes to be removed
  mount:
    name="{{item.mountpoint}}"
    src="/dev/{{item.vg|default(lvm_vars.vg)}}/{{item.lv}}"
    fstype="{{item.fstype | default('ext4')}}"
    state=absent
  when: lvm_vars.volumes is defined and
        (lvm_vars.vg is defined or lvm_vars.vgs is defined) and
        (item.state|default('present')) == 'absent'
  with_items:
    "{{ lvm_vars.volumes }}"

- name: Set up logical volumes
  lvol:
    vg="{{item.vg|default(lvm_vars.vg)}}"
    lv="{{item.lv}}"
    size="{{item.size}}"
    state="{{ item.state|default('present') }}"
    force="{{ item.state is defined and item.state == 'absent' }}"
  when: lvm_vars.volumes is defined and
        (lvm_vars.vg is defined or lvm_vars.vgs is defined)
  with_items:
    "{{ lvm_vars.volumes }}"

- name: Format logical volumes
  filesystem:
    fstype="{{item.fstype|default('ext4')}}"
    dev="/dev/{{item.vg|default(lvm_vars.vg)}}/{{item.lv}}"
  when: (item.state|default('present')) != 'absent'
  with_items:
    "{{ lvm_vars.volumes }}"
