---
- name: Set up logical volumes
  lvol:
    vg="{{ vg.key }}"
    lv="{{ item.key }}"
    size="{{ item.value.size }}"
  with_dict:
    "{{ vg.value.lvs }}"

- name: Format logical volumes
  filesystem:
    fstype="{{ item.value.fstype|default('ext4') }}"
    dev="/dev/{{ vg.key }}/{{ item.key }}"
  with_dict:
    "{{ vg.value.lvs }}"
