---
# Set up partitions using logical volume management (LVM)

- name: Install LVM package
  apt: name=lvm2 state=installed

- include: vgs.yml

- include: lvs.yml
  when: vg.value.lvs is defined and vg.value.lvs
  with_dict:
    "{{ lvm }}"
  loop_control:
    loop_var: vg

- include: mounts.yml
  when: vg.value.lvs is defined and vg.value.lvs
  with_dict:
    "{{ lvm }}"
  loop_control:
    loop_var: vg

- include: resize-fs.yml
  tags: qwex
  when: vg.value.lvs is defined and vg.value.lvs
  with_dict:
    "{{ lvm }}"
  loop_control:
    loop_var: vg

- include: tune2fs.yml
  when: vg.value.lvs is defined and vg.value.lvs
  with_dict:
    "{{ lvm }}"
  loop_control:
    loop_var: vg
