---
# Set up partitions using logical volume management (LVM)

- name: Install LVM package
  apt: name=lvm2 state=installed

- include: vgs.yml
- include: lvs.yml
- include: mounts.yml
- include: resize-fs.yml
