---
- name: Create mount points
  file:
    path="{{ item.value.mountpoint }}"
    state=directory
    mode="{{ item.value.mode|default('0755') }}"
    owner="{{ item.value.owner|default(omit) }}"
    group="{{ item.value.group|default(omit) }}"
  with_dict:
    "{{ vg.value.lvs }}"

- name: Mount logical volumes
  mount:
    name="{{ item.value.mountpoint }}"
    src="/dev/{{ vg.key }}/{{ item.key }}"
    fstype="{{ item.value.fstype|default(lvm_default_fstype) }}"
    state=mounted
    opts="{{ item.value.options|default(omit) }}"
  with_dict:
    "{{ vg.value.lvs }}"
