---
- name: Resize filesystem if needed
  shell: >
    resize2fs "/dev/{{ vg.key }}/{{ item.key }}" 2>&1 |
    awk '
    BEGIN { failed = 1 }
    /The filesystem on.*is now.*long/
    {  print "changed"; failed = 0 }
    /Nothing to do!/
    {  print "not changed"; failed = 0 }
    END { if (failed) print "failed" }'
  when: item.value.fstype is not defined or
        item.value.fstype in ('ext3', 'ext4')
  changed_when: resize2fs.stdout == 'changed'
  failed_when: resize2fs.stdout == 'failed'
  register: resize2fs
  with_dict:
    "{{ vg.value.lvs }}"
