---
- name: Set up volume group
  lvg: vg={{lvm_vars.vg}}
       pvs={{ lvm_vars.pvs|join(',') }}
       state=present
  when: lvm_vars.vg is defined

- name: Set up multiple volume groups
  lvg: vg={{item.vg}} pvs={{ item.pvs|join(',') }}
  when: lvm_vars.vgs is defined
  with_items:
    "{{ lvm_vars.vgs }}"
